AssetTracker/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracker.Core.BLL;
using AssetTracker.Core.Models;
using AssetTracker.Core.Models.EntityModel;
using AssetTracker.Core.Models.Interfaces.IManager;

namespace AssetTracker.Controllers
{
    public class CategoryController : Controller
    {
        private IGeneralCategoryManager _generalCategoryManager;
        private ICategoryManager _categoryManager;

        public CategoryController(IGeneralCategoryManager generalCategoryManager, ICategoryManager categoryManager)
        {
            _generalCategoryManager = generalCategoryManager;
            _categoryManager = categoryManager;
        }
        // GET: Category
        public ActionResult Index()
        {
            var categories = _categoryManager.GetAll();
            return View(categories);
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = _categoryManager.GetById((int) id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName");
            ViewBag.Categories = new List<SelectListItem>();
            return View();
        }
        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,GeneralCategoryID,CategoryName,CategoryCode,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                if(_categoryManager.Insert(category))
                    return RedirectToAction("Index");
                ModelState.AddModelError("","Something went worng");
            }

            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName");
            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = _categoryManager.GetById((int) id);
            if (category == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName");
            return View(category);
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,GeneralCategoryID,CategoryName,CategoryCode,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                if(_categoryManager.Edit(category))
                    return RedirectToAction("Index");
                ModelState.AddModelError("","Something went worng");
            }
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName");
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = _categoryManager.GetById((int)id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if(_categoryManager.Delete(id))
                return RedirectToAction("Index");
            Category category = _categoryManager.GetById((int)id);
            return View(category);
        }
        public JsonResult IsCategoryCodeAvailableWithId(int generalCategoryId, string categoryCode,int categoryId) 
        {
            return Json(_categoryManager.IsCategoryCodeAvailable(generalCategoryId, categoryCode, categoryId), JsonRequestBehavior.DenyGet);
        }
       public JsonResult IsCategoryCodeAvailable(int generalCategoryId, string categoryCode) 
        {
            return Json(_categoryManager.IsCategoryCodeAvailable(generalCategoryId, categoryCode), JsonRequestBehavior.DenyGet);
        }
        public JsonResult IsCategoryNameAvailable(int generalCategoryId, string categoryName) 
        {
            return Json(_categoryManager.IsCategoryNameAvailable(generalCategoryId, categoryName), JsonRequestBehavior.DenyGet);
        }
        public JsonResult IsCategoryNameAvailableWithId(int generalCategoryId, string categoryName, int categoryId) 
        {
            return Json(_categoryManager.IsCategoryNameAvailable(generalCategoryId, categoryName, categoryId), JsonRequestBehavior.DenyGet);
        }

        public JsonResult GetAllByGeneralCategoryId(int generalCategoryId)
        {
            var categories = _categoryManager.GetAllByGeneralCategoryId(generalCategoryId)
                .Select(content => new
                {
                    content.CategoryID,
                    content.CategoryCode,
                    content.CategoryName,
                    content.CategoryDescription,
                    content.GeneralCategoryID,
                    content.GeneralCategory.GeneralCategoryName
                });
            return Json(categories, JsonRequestBehavior.DenyGet);
        }

        
    }
}

AssetTracker/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracker.Core.BLL;
using AssetTracker.Core.Models;
using AssetTracker.Core.Models.EntityModel;
using AssetTracker.Core.Models.Interfaces.IManager;

namespace AssetTracker.Controllers
{
    public class EmployeeController : Controller
    {
       
        private IEmployeeManager _employeeManager;
        private IOrganizationManager _organizationManager;
        private IOrganizationBranchManager _organizationBranchManager;
        private IDesignationManager _designationManager;
        private IDepartmentManager _departmentManager;

        public EmployeeController(IEmployeeManager employeeManager, IOrganizationManager organizationManager,
            IOrganizationBranchManager organizationBranchManager, IDesignationManager designationManager,
            IDepartmentManager departmentManager)
        {
            _employeeManager = employeeManager;
            _organizationManager = organizationManager;
            _organizationBranchManager = organizationBranchManager;
            _designationManager = designationManager;
            _departmentManager = departmentManager;
        }
        // GET: Employee
        public ActionResult Index()
        {
            var employees = _employeeManager.GetAll();
            return View(employees);
        }

        // GET: Employee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = _employeeManager.GetById((int)id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            ViewBag.Organizations = new SelectList(_organizationManager.GetAll(), "OrganizationID", "OrganizationName");
            ViewBag.Designations = new SelectList(_designationManager.GetAll(), "DesignationID", "DesignationName");
            ViewBag.OrganizationBranches = Enumerable.Empty<SelectListItem>();
            ViewBag.Departments = Enumerable.Empty<SelectListItem>();
            return View();
        }

        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeID,DepartmentID,EmployeeName,DesignationID,ContactNo,Email")] Employee employee,int organizationId,int organizationBranchId)
        {
            if (ModelState.IsValid)
            {
                if (_employeeManager.Insert(employee))
                    return RedirectToAction("Index");
                ModelState.AddModelError("","Something went worng");
            }

            ViewBag.Organizations = new SelectList(_organizationManager.GetAll(), "OrganizationID", "OrganizationName", organizationId);
            ViewBag.Designations = new SelectList(_designationManager.GetAll(), "DesignationID", "DesignationName");
            ViewBag.OrganizationBranches = new SelectList(_organizationBranchManager.GetAll(), "OrganizationBranchID", "OrganizationBranchName", organizationBranchId);
            ViewBag.Departments = new SelectList(_departmentManager.GetAll(),"DepartmentID","DepartmentName");
            return View(employee);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = _employeeManager.GetById((int)id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.Organizations = new SelectList(_organizationManager.GetAll(), "OrganizationID", "OrganizationName", employee.Department.OrganizationBranch.OrganizationID);
            ViewBag.Designations = new SelectList(_designationManager.GetAll(), "DesignationID", "DesignationName");
            ViewBag.OrganizationBranches = new SelectList(_organizationBranchManager.GetAll(), "OrganizationBranchID", "OrganizationBranchName", employee.Department.OrganizationBranchID);
            ViewBag.Departments = new SelectList(_departmentManager.GetAll(), "DepartmentID", "DepartmentName");
            return View(employee);
        }

        // POST: Employee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeID,DepartmentID,EmployeeName,DesignationID,ContactNo,Email")] Employee employee, int organizationId, int organizationBranchId)
        {
            if (ModelState.IsValid)
            {
                if (_employeeManager.Edit(employee))
                    return RedirectToAction("Index");
                ModelState.AddModelError("", "Something went worng");
            }
            ViewBag.Organizations = new SelectList(_organizationManager.GetAll(), "OrganizationID", "OrganizationName", organizationId);
            ViewBag.Designations = new SelectList(_designationManager.GetAll(), "DesignationID", "DesignationName");
            ViewBag.OrganizationBranches = new SelectList(_organizationBranchManager.GetAllByOrganizationId(organizationId), "OrganizationBranchID", "OrganizationBranchName", organizationBranchId);
            ViewBag.Departments = new SelectList(_departmentManager.GetAllByOrganizationBranchId(organizationBranchId), "DepartmentID", "DepartmentName");
            return View(employee);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = _employeeManager.GetById((int) id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if(_employeeManager.Delete(id))
                return RedirectToAction("Index");
            ModelState.AddModelError("","Something went worng");
            Employee employee = _employeeManager.GetById(id);
            return View(employee);
        }
        
    }
}

AssetTracker/Controllers/VendorController.cs
using AssetTracker.Core.Models.EntityModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTracker.Core.BLL;
using AssetTracker.Core.Models.Interfaces.IManager;

namespace AssetTracker.Controllers
{
    public class VendorController : Controller
    {
        private IVendorManager _vendorManager;

        public VendorController(IVendorManager vendorManager)
        {
            _vendorManager = vendorManager;
        }
        // GET: Vendor
        public ActionResult Index()
        {
            var vendors = _vendorManager.GetAll();
            return View(vendors);
        }

        // GET: Vendor/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Vendor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vendor/Create
        [HttpPost]
        public ActionResult Create(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                if (_vendorManager.Insert(vendor))
                    return RedirectToAction("Index");
                ModelState.AddModelError("","Something went worng");
            }
            return View(vendor);
        }

        // GET: Vendor/Edit/5
        public ActionResult Edit(int id)
        {
            var vendor = _vendorManager.GetById(id);
            return View(vendor);
        }

        // POST: Vendor/Edit/5
        [HttpPost]
        public ActionResult Edit(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                if(_vendorManager.Edit(vendor))
                    return RedirectToAction("Index");
                ModelState.AddModelError("", "Something went worng");
            }
            return View(vendor);
        }

        // GET: Vendor/Delete/5
        public ActionResult Delete(int id)
        {
            var vendor = _vendorManager.GetById(id);
            return View(vendor);
        }

        // POST: Vendor/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (_vendorManager.Delete(id))
                return RedirectToAction("Index");
            ModelState.AddModelError("","Something went worng");
            var vendor = _vendorManager.GetById(id);
            return View(vendor);
        }

        public JsonResult IsVendorNameAvailable(string vendorName,int? vendorId)
        {
            if (vendorId == null)
                vendorId = 0;
            return Json(_vendorManager.IsVendorNameAvailable(vendorName, (int)vendorId),JsonRequestBehavior.DenyGet);
        }
    }
}

AssetTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Asset Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="shortcut icon" href="~/Images/Asset-tracker-4.png">
    @RenderSection("css", required: false)

</head>
<body class="homepage">
    <header id="header">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index","Home")">
                        <img style="height: 45px;
    width: 169px;" src="~/Images/Asset-tracker-3.png" alt="logo">
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-left">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Asset Purchase <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Entry Asset Purchase</a></li>
                                <li><a href="#">View Asset Purchases</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Asset Registration <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Entry Asset Registration</a></li>
                                <li><a href="#">View Asset Registrations</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Asset Movement <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Entry Asset Movement</a></li>
                                <li><a href="#">View Asset Movements</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Asset Distribution <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Entry Asset Distribution</a></li>
                                <li><a href="#">View Asset Distributions</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu extra-submenu">
                            <a tabindex="-1" href="#">Setup <i class="fa fa-angle-down"></i></a>

                            <ul class="dropdown-menu extra-menu">
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Organization <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","Organization")">Create Organization</a></li>
                                        <li><a href="@Url.Action("Index","Organization")">View Organizations</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Organization Branch <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","OrganizationBranch")">Create Organization Branch</a></li>
                                        <li><a href="@Url.Action("Index","OrganizationBranch")">View Organization Branches</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Asset Location <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="#">Create Asset Location</a></li>
                                        <li><a href="#">View Asset Locations</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">General Category <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","GeneralCategory")">Create General Category</a></li>
                                        <li><a href="@Url.Action("Index","GeneralCategory")">View General Categories</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Category <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","Category")">Create Category</a></li>
                                        <li><a href="@Url.Action("Index","Category")">View Categories</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Sub Category <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","SubCategory")">Create Sub Category</a></li>
                                        <li><a href="@Url.Action("Index","SubCategory")">View Sub Categories</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Product Category <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","DetailCategory")">Create Product Category</a></li>
                                        <li><a href="@Url.Action("Index","DetailCategory")">View Product Categories</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Vendor <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","Vendor")">Create Vendor</a></li>
                                        <li><a href="@Url.Action("Index","Vendor")">View Vendors</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Employee <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","Employee")">Create Employee</a></li>
                                        <li><a href="@Url.Action("Index","Employee")">View Employees</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Department <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create", "Department")">Create Department</a></li>
                                        <li><a href="@Url.Action("Index", "Department")">View Departments</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu dropdown">
                                    <a href="#">Designation <i class="fa fa-angle-right"></i></a>
                                    <ul class="dropdown-menu extra-dropdown">
                                        <li><a href="@Url.Action("Create","Designation")">Create Designation</a></li>
                                        <li><a href="@Url.Action("Index", "Designation")">View Designations</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="body-content">
        @RenderBody()
    </div>

    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 <a target="_blank" href="@Url.Action("Index","Home")"
                                   >3 Loosers</a>. All Rights Reserved.
                </div>
                @*<div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>*@
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="~/Scripts/main.js"></script>*@
    @RenderSection("scripts", required: false)
</body>
</html>