AssetTracker/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracker.Core.BLL;
using AssetTracker.Core.Models;
using AssetTracker.Core.Models.EntityModel;
using AssetTracker.Core.Models.Interfaces.IManager;

namespace AssetTracker.Controllers
{
    public class SubCategoryController : Controller
    {
        private IGeneralCategoryManager _generalCategoryManager;
        private ICategoryManager _categoryManager;
        private ISubCategoryManager _subCategoryManager;

        public SubCategoryController(IGeneralCategoryManager generalCategoryManager, ICategoryManager categoryManager, ISubCategoryManager subCategoryManager)
        {
            _generalCategoryManager = generalCategoryManager;
            _categoryManager = categoryManager;
            _subCategoryManager = subCategoryManager;
        }

        // GET: SubCategory
        public ActionResult Index()
        {
            var subCategories = _subCategoryManager.GetAll();
            return View(subCategories);
        }

        // GET: SubCategory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subCategory = _subCategoryManager.GetById((int) id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            return View(subCategory);
        }

        // GET: SubCategory/Create
        public ActionResult Create()
        {
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(),"GeneralCategoryID","GeneralCategoryName");

            ViewBag.Categories = Enumerable.Empty<SelectListItem>();
            return View();
        }

        // POST: SubCategory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubCategoryID,CategoryID,SubCategoryName,SubCategoryCode,SubCategoryDescription")] SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
               if(_subCategoryManager.Insert(subCategory))
                    return RedirectToAction("Index");
            }

            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName",subCategory.Category.GeneralCategoryID);
            ViewBag.Categories = new SelectList(_categoryManager.GetAll(), "CategoryID", "CategoryName", subCategory.CategoryID);
            ModelState.AddModelError("","Something went worng!");
            
            return View(subCategory);
        }

        // GET: SubCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subCategory = _subCategoryManager.GetById((int) id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName", subCategory.Category.GeneralCategoryID);
            ViewBag.Categories = new SelectList(_categoryManager.GetAll(), "CategoryID", "CategoryName", subCategory.CategoryID);
            return View(subCategory);
        }

        // POST: SubCategory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubCategoryID,CategoryID,SubCategoryName,SubCategoryCode,SubCategoryDescription")] SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
               if(_subCategoryManager.Edit(subCategory))
                    return RedirectToAction("Index");
            }
            var category = _categoryManager.GetById(subCategory.CategoryID);

            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName", category.GeneralCategory.GeneralCategoryID);
            ViewBag.Categories = new SelectList(_categoryManager.GetAll(), "CategoryID", "CategoryName", subCategory.CategoryID);
            ModelState.AddModelError("","Something went worng");
            return View(subCategory);
        }

        // GET: SubCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subCategory = _subCategoryManager.GetById((int) id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            return View(subCategory);
        }

        // POST: SubCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if(_subCategoryManager.Delete(id))
                return RedirectToAction("Index");
            SubCategory subCategory = _subCategoryManager.GetById((int) id);
            return View(subCategory);
        }
        public ActionResult IsNameAvailable(string subCategoryName,int categoryId)
        {
            return Json(_subCategoryManager.IsSubCategoryNameAvailable(subCategoryName,categoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsNameAvailableWithId(string subCategoryName, int subCategoryId, int categoryId) 
        {
            return Json(_subCategoryManager.IsSubCategoryNameAvailable(subCategoryName,subCategoryId, categoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsCodeAvailable(string subCategoryCode, int categoryId) 
        {
            return Json(_subCategoryManager.IsSubCategoryCodeAvailable(subCategoryCode, categoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsCodeAvailableWithId(string subCategoryCode,int subCategoryId, int categoryId)
        {
            return Json(_subCategoryManager.IsSubCategoryCodeAvailable(subCategoryCode, subCategoryId,categoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetAllByCategoryId(int categoryId)
        {
            var subCategories = _subCategoryManager.GetAllByCategoryId(categoryId)
                .Select(content => new
                {
                    content.SubCategoryID,
                    content.SubCategoryName,
                    content.SubCategoryCode,
                    content.SubCategoryDescription,
                    content.CategoryID
                });
            return Json(subCategories, JsonRequestBehavior.AllowGet);
        }

    }
}

AssetTracker/Views/SubCategory/Create.cshtml
@model AssetTracker.Core.Models.SubCategory

@{
    ViewBag.Title = "Create";
}
<div class="container">
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="panel panel-primary">
                <div class="panel-heading">Create Sub Category</div>
                <div class="panel-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("General Category", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("GeneralCategoryID", ViewBag.GeneralCategories as IEnumerable<SelectListItem>, "Select a General Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryID, ViewBag.Categories as IEnumerable<SelectListItem>, "Select a Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SubCategoryName, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryName, "", new { @class = "text-danger" })
                            <span class="text-danger" id="sub-category-name-exist"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubCategoryCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SubCategoryCode, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryCode, "", new { @class = "text-danger" })
                            <span class="text-danger" id="sub-category-code-exist"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubCategoryDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SubCategoryDescription, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-success" />
                            <input type="button" value="Cancel" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Home")'" />
                            <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "SubCategory")'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   <script src="~/Scripts/Asset Tracker/SubCategory/Create.js"></script>
}

AssetTracker/Views/SubCategory/Delete.cshtml
@model AssetTracker.Core.Models.SubCategory

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="form-horizontal">
        <div class="panel panel-primary">
            <div class="panel-heading">Delete Organization</div>
            <div class="panel-body">
                <h3>Are you sure you want to delete this?</h3>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Category.CategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Category.CategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryCode)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryDescription)
                    </dd>

                </dl>

                @using (Html.BeginForm()) {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <input type="button" value="Edit" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "SubCategory", new { id = Model.SubCategoryID })'" />
                            <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "SubCategory")'" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

AssetTracker/Views/SubCategory/Details.cshtml
@model AssetTracker.Core.Models.SubCategory

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="form-horizontal">
        <div class="panel panel-primary">
            <div class="panel-heading">Sub Category Details</div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Category.CategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Category.CategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryCode)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategoryDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategoryDescription)
                    </dd>

                </dl>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Edit" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "SubCategory", new { id = Model.SubCategoryID })'" />
                        <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "SubCategory")'" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AssetTracker/Views/SubCategory/Edit.cshtml
@model AssetTracker.Core.Models.SubCategory

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="panel panel-primary">
                <div class="panel-heading">Edit Category</div>
                <div class="panel-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.SubCategoryID)
                    <div class="form-group">
                        @Html.Label("General Category", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("GeneralCategoryID", ViewBag.GeneralCategories as IEnumerable<SelectListItem>, "Select a General Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryID, ViewBag.Categories as IEnumerable<SelectListItem>, "Select a Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SubCategoryName, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryName, "", new { @class = "text-danger" })
                            <span class="text-danger" id="sub-category-name-exist"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubCategoryCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SubCategoryCode, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryCode, "", new { @class = "text-danger" })
                            <span class="text-danger" id="sub-category-code-exist"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SubCategoryDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SubCategoryDescription, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-success" />
                            <input type="button" value="Cancel" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Home")'" />
                            <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "SubCategory")'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Asset Tracker/SubCategory/Edit.js"></script>
}

AssetTracker/Views/SubCategory/Index.cshtml
@model IEnumerable<AssetTracker.Core.Models.SubCategory>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">View All Sub Categories</div>
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-12">
                    <input type="button" value="Create" class="btn btn-success" onclick="location.href = '@Url.Action("Create", "SubCategory")'" />

                </div>
            </div>
            <table class="table table-hover table-background table-bordered">
                <tr>
                    <th>
                        @Html.DisplayName("General Category")
                    </th>
                    <th>
                        @Html.DisplayName("Category")
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubCategoryName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubCategoryCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubCategoryDescription)
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>

                @foreach (var item in Model) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category.GeneralCategory.GeneralCategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Category.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubCategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubCategoryCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubCategoryDescription)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new {id = item.SubCategoryID}) |
                            @Html.ActionLink("Details", "Details", new {id = item.SubCategoryID}) |
                            @Html.ActionLink("Delete", "Delete", new {id = item.SubCategoryID})
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>