AssetTracker/Controllers/DetailCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetTracker.Core.BLL;
using AssetTracker.Core.Models;
using AssetTracker.Core.Models.EntityModel;
using AssetTracker.Core.Models.Interfaces.IManager;

namespace AssetTracker.Controllers
{
    public class DetailCategoryController : Controller
    {
        
        private IGeneralCategoryManager _generalCategoryManager;
        private ICategoryManager _categoryManager;
        private ISubCategoryManager _subCategoryManager;
        private IDetailCategoryManager _detailCategoryManager;

        public DetailCategoryController(IGeneralCategoryManager generalCategoryManager, ICategoryManager categoryManager, ISubCategoryManager subCategoryManager, IDetailCategoryManager detailCategoryManager)
        {
            _generalCategoryManager = generalCategoryManager;
            _categoryManager = categoryManager;
            _subCategoryManager = subCategoryManager;
            _detailCategoryManager = detailCategoryManager;
        }

        // GET: DetailCategory
        public ActionResult Index()
        {
            var detailCategories = _detailCategoryManager.GetAll();
            return View(detailCategories);
        }

        // GET: DetailCategory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailCategory detailCategory = _detailCategoryManager.GetById((int)id);
            if (detailCategory == null)
            {
                return HttpNotFound();
            }
            return View(detailCategory);
        }

        // GET: DetailCategory/Create
        public ActionResult Create()
        {
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName");
            ViewBag.Categories = Enumerable.Empty<SelectListItem>();
            ViewBag.SubCategories = Enumerable.Empty<SelectListItem>();

            return View();
        }

        // POST: DetailCategory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DetailCategoryID,SubCategoryID,DetailCategoryName,DetailCategoryCode,DetailCategoryDescription")] DetailCategory detailCategory)
        {
            if (ModelState.IsValid)
            {
                _detailCategoryManager.Insert(detailCategory);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("","Something went wrong");
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName", detailCategory.SubCategory.Category.GeneralCategoryID);
            ViewBag.Categories = new SelectList(_categoryManager.GetAll(), "CategoryID", "CategoryName", detailCategory.SubCategory.CategoryID);
            ViewBag.SubCategories = new SelectList(_subCategoryManager.GetAll(), "SubCategoryID", "SubCategoryName", detailCategory.SubCategoryID);
            return View(detailCategory);
        }

        // GET: DetailCategory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailCategory detailCategory = _detailCategoryManager.GetById((int) id);
            if (detailCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName", detailCategory.SubCategory.Category.GeneralCategoryID);
            ViewBag.Categories = new SelectList(_categoryManager.GetAll(), "CategoryID", "CategoryName", detailCategory.SubCategory.CategoryID);
            ViewBag.SubCategories = new SelectList(_subCategoryManager.GetAll(), "SubCategoryID", "SubCategoryName", detailCategory.SubCategoryID);
            return View(detailCategory);
        }

        // POST: DetailCategory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DetailCategoryID,SubCategoryID,DetailCategoryName,DetailCategoryCode,DetailCategoryDescription")] DetailCategory detailCategory)
        {
            if (ModelState.IsValid)
            {
                _detailCategoryManager.Edit(detailCategory);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something went wrong");
            ViewBag.GeneralCategories = new SelectList(_generalCategoryManager.GetAll(), "GeneralCategoryID", "GeneralCategoryName", detailCategory.SubCategory.Category.GeneralCategoryID);
            ViewBag.Categories = new SelectList(_categoryManager.GetAll(), "CategoryID", "CategoryName", detailCategory.SubCategory.CategoryID);
            ViewBag.SubCategories = new SelectList(_subCategoryManager.GetAll(), "SubCategoryID", "SubCategoryName", detailCategory.SubCategoryID);
            return View(detailCategory);
        }

        // GET: DetailCategory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailCategory detailCategory = _detailCategoryManager.GetById((int)id);
            if (detailCategory == null)
            {
                return HttpNotFound();
            }
            return View(detailCategory);
        }

        // POST: DetailCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if(_detailCategoryManager.Delete(id))
                return RedirectToAction("Index");
            DetailCategory detailCategory = _detailCategoryManager.GetById((int)id);
            return View(detailCategory);
        }
        public ActionResult IsNameAvailable(string detailCategoryName, int subCategoryId)
        {
            return Json(_detailCategoryManager.IsDetailCategoryNameAvilable(detailCategoryName, subCategoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsNameAvailableWithId(string detailCategoryName, int detailCategoryId, int subCategoryId)
        {
            return Json(_detailCategoryManager.IsDetailCategoryNameAvilable(detailCategoryName, detailCategoryId, subCategoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsCodeAvailable(string detailCategoryCode, int subCategoryId)
        {
            return Json(_detailCategoryManager.IsDetailCategoryCodeAvilable(detailCategoryCode, subCategoryId), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsCodeAvailableWithId(string detailCategoryCode, int detailCategoryId, int subCategoryId)
        {
            return Json(_detailCategoryManager.IsDetailCategoryCodeAvilable(detailCategoryCode, detailCategoryId, subCategoryId), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllBySubCategoryId(int subCategoryId)
        {
            var detailCategories = _detailCategoryManager
                .GetAllBySubCategoryId(subCategoryId)
                .Select(c => new
                {
                    c.DetailCategoryID,
                    c.SubCategoryID,
                    c.DetailCategoryCode,
                    c.DetailCategoryName,
                    c.DetailCategoryDescription
                }).ToList();

            return Json(detailCategories, JsonRequestBehavior.AllowGet);
        }
    }
}

AssetTracker/Views/DetailCategory/Create.cshtml
@model AssetTracker.Core.Models.DetailCategory

@{
    ViewBag.Title = "Create";
}

<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="panel panel-primary">
                <div class="panel-heading">Create Detail Category</div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.Label("General Category", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("GeneralCategoryID", ViewBag.GeneralCategories as IEnumerable<SelectListItem>, "Select a General Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("CategoryID", ViewBag.Categories as IEnumerable<SelectListItem>, "Select a Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SubCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.SubCategoryID, ViewBag.SubCategories as IEnumerable<SelectListItem>, "Select a Sub Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                                @Html.ValidationMessageFor(model => model.SubCategoryID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DetailCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DetailCategoryName, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                                @Html.ValidationMessageFor(model => model.DetailCategoryName, "", new { @class = "text-danger" })
                                <span class="text-danger" id="detail-category-name-exist"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DetailCategoryCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DetailCategoryCode, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                                @Html.ValidationMessageFor(model => model.DetailCategoryCode, "", new { @class = "text-danger" })
                                <span class="text-danger" id="detail-category-code-exist"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DetailCategoryDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DetailCategoryDescription, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                                @Html.ValidationMessageFor(model => model.DetailCategoryDescription, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <<div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-success" />
                                <input type="button" value="Cancel" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Home")'" />
                                <input type="button" value="View All" class="btn btn-info" onclick="location.href = '@Url.Action("Index", "DetailCategory")'" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Asset Tracker/DetailCategory/Create.js"></script>
}

AssetTracker/Views/DetailCategory/Delete.cshtml
@model AssetTracker.Core.Models.DetailCategory

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="form-horizontal">
        <div class="panel panel-primary">
            <div class="panel-heading">Delete Organization</div>
            <div class="panel-body">
                <h3>Are you sure you want to delete this?</h3>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategory.SubCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategory.SubCategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DetailCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DetailCategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DetailCategoryCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DetailCategoryCode)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DetailCategoryDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DetailCategoryDescription)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <input type="button" value="Edit" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "DetailCategory", new { id = Model.DetailCategoryID })'" />
                            <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "DetailCategory")'" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

AssetTracker/Views/DetailCategory/Details.cshtml
@model AssetTracker.Core.Models.DetailCategory

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="form-horizontal">
        <div class="panel panel-primary">
            <div class="panel-heading">Detail Category Details</div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.SubCategory.SubCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SubCategory.SubCategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DetailCategoryName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DetailCategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DetailCategoryCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DetailCategoryCode)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DetailCategoryDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DetailCategoryDescription)
                    </dd>

                </dl>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Edit" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit", "DetailCategory", new { id = Model.DetailCategoryID })'" />
                    <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "DetailCategory")'" />
                </div>
            </div>
        </div>
    </div>
</div>
</div>

AssetTracker/Views/DetailCategory/Edit.cshtml
@model AssetTracker.Core.Models.DetailCategory

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <br />
            <div class="panel panel-primary">
                <div class="panel-heading">Edit Detail Category</div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.DetailCategoryID)

                        <div class="form-group">
                            @Html.Label("General Category", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("GeneralCategoryID", ViewBag.GeneralCategories as IEnumerable<SelectListItem>, "Select a General Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("CategoryID", ViewBag.Categories as IEnumerable<SelectListItem>, "Select a Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SubCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.SubCategoryID, ViewBag.SubCategories as IEnumerable<SelectListItem>, "Select a Sub Category", htmlAttributes: new { @class = "form-control text-box-border-color" })
                                @Html.ValidationMessageFor(model => model.SubCategoryID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DetailCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DetailCategoryName, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                                @Html.ValidationMessageFor(model => model.DetailCategoryName, "", new { @class = "text-danger" })
                                <span class="text-danger" id="detail-category-name-exist"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DetailCategoryCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DetailCategoryCode, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                                @Html.ValidationMessageFor(model => model.DetailCategoryCode, "", new { @class = "text-danger" })
                                <span class="text-danger" id="detail-category-code-exist"></span>

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DetailCategoryDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DetailCategoryDescription, new { htmlAttributes = new { @class = "form-control text-box-border-color" } })
                                @Html.ValidationMessageFor(model => model.DetailCategoryDescription, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-success" />
                                <input type="button" value="Cancel" class="btn btn-danger" onclick="location.href = '@Url.Action("Index", "Home")'" />
                                <input type="button" value="View All" class="btn btn-info" onclick="location.href='@Url.Action("Index", "DetailCategory")'" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Asset Tracker/DetailCategory/Edit.js"></script>
}

AssetTracker/Views/DetailCategory/Index.cshtml
@model IEnumerable<AssetTracker.Core.Models.DetailCategory>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">View All Detail Categories</div>
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-12">
                    <input type="button" value="Create" class="btn btn-success" onclick="location.href = '@Url.Action("Create", "DetailCategory")'" />

                </div>
            </div>
            <table class="table table-hover table-background table-bordered">
                <tr>
                    <th>
                        @Html.DisplayName("General Category")
                    </th>
                    <th>
                        @Html.DisplayName("Category")
                    </th>
                    <th>
                        @Html.DisplayName("Sub Category")
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DetailCategoryName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DetailCategoryCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DetailCategoryDescription)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubCategory.Category.GeneralCategory.GeneralCategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubCategory.Category.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SubCategory.SubCategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DetailCategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DetailCategoryCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DetailCategoryDescription)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.DetailCategoryID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.DetailCategoryID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.DetailCategoryID })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/datatablejs")
    <script>
        $(document).ready(function () {
            $(".table").DataTable();
        });
    </script>
}